### ISSUE TITLE
JSON file causing infinite loop?

### ISSUE THREAD

**Issue by ad1c** [kgabis/parson#129]
json_parse_file() seems to get hung parsing the JSON file downloaded from this web page:

https://clublog.freshdesk.com/support/solutions/articles/3000064883-list-of-club-log-and-lotw-users

I'm using the sources from:  kgabis-parson-0341880.zip

I was able to parse it no problem in Perl.

**Comment by kgabis** [comment]
It works but takes forever because parson uses an array instead of a dictionary to implement objects. So adding a value to object takes O(n) and this file has over 150k objects. I know it's terrible and after a certain number of keys current implementation should be replaced with a dictionary but I don't plan on doing this because implementing it would take a lot of time and possibly introduce many bugs.

**Comment by ad1c** [comment]
Thanks.
