### ISSUE TITLE
Parson cannot parse generated document

### ISSUE THREAD

**Issue by sgh** [kgabis/parson#161]
Using parson my software has generated the following json document.

{"xyz":[0,6.9041432094973937e-310,6.9041432094973937e-310]}

Parson however cannot parse the document.

In my debugger the doubles I pass to json_array_append_number look exactly like the ones written.

The problem seems to be errno being set to ERANGE after the call to strtod in parse_number_value during parsing.

The strtod manpage say the following regarding ERANGE.

"If the correct value would cause underflow, a value with magnitude no larger than DBL_MIN, FLT_MIN, or LDBL_MIN is returned and ERANGE is stored in errno."

So I guess the solution could be simmilar to this :

```
static JSON_Value * parse_number_value(const char **string) {
    char *end;
    double number = 0;
    errno = 0;
    number = strtod(*string, &end);
    if ((errno!=0 && errno!=ERANGE) || !is_decimal(*string, end - *string)) {
        return NULL;
    }
    *string = end;
    return json_value_init_number(number);
}
```

![Screenshot_20210525_103312](https://user-images.githubusercontent.com/192802/119466498-f7ef1a00-bd44-11eb-9822-5cec676156be.png)

**Comment by kgabis** [comment]
Thanks, I've fixed it in https://github.com/kgabis/parson/commit/2d7b3ddf1280bf7f5ad82d26e09252240e7c4557.

**Comment by abkarcher** [comment]
Hello,

Not an issue, but just wanted to leave a note here. The fix creates (irrelevant) build warnings when building with -Wfloat-equal. Some users may require these warnings to be dealt with - this can be done by using
`(errno == ERANGE && (number <= -HUGE_VAL || number >= HUGE_VAL)`
in place of 
`(errno == ERANGE && (number == -HUGE_VAL || number == HUGE_VAL)`

From my understanding, due to the definite nature of HUGE_VAL, this will not alter the logic at all. 

Thanks,
Andrew
