### ISSUE TITLE
realloc is faster and safer than malloc + memcpy + free

### ISSUE THREAD

**Issue by GottZ** [kgabis/parson#215]
this basically adds to #63

I've just audited the library code for a personal use project and noticed the library is constantly creating new heap allocations for extending objects, arrays and strings.

for example: https://github.com/kgabis/parson/blob/ba29f4eda9ea7703a9f6a9cf2b0532a2605723c3/parson.c#L898-L905
https://github.com/kgabis/parson/blob/ba29f4eda9ea7703a9f6a9cf2b0532a2605723c3/parson.c#L751-L760

is there any particular reason to re-allocating like this, over just using `buffer = realloc(buffer, buffer_size);`?

I suspect the lib will see a negative speed impact with big json blobs because of this, similar to the GTA5 loading screen situation.

in case you are unaware what realloc does:
it tells the kernel to grow the allocation.
if the kernel did not allocate adjacent memory in it's memory table yet, it will just increase the allocation without a memcpy successfully.
if it encounters other allocated data next to it, the kernel does the memcpy for you, so you don't even have to deal with it. in some cases it even changes memory page allocations under the hood to make space for a re-allocation.
the benefit of this: the heap allocation grows without wasting cpu cycles on memory copy opcodes.

another benefit: it would reduce potential use-after-free bugs in code-bases using this library.

please just let me know if this was an oversight or actually intended, and if I should just fix it quickly and push a PR.

**Comment by kgabis** [comment]
IIRC the problem with GTAV loading screen was caused by using a linear search every time something was added to an object, not by not using realloc.
I suspect using realloc in parson would be better, but I do grow size by a factor of 2 when it needs resizing so it might not be *that* bad (I have not measured it though). Also, this would require changing the api around custom allocators and I'd rather not do that. So in a nutshell: using realloc would make parson run faster, but I have no idea how much on average and I'm not willing to change the API at this point.
