### ISSUE TITLE
Logic problem for `json_array_remove()`

### ISSUE THREAD

**Issue by Ron89** [kgabis/parson#81]
According to JSON standard, objects in array is supposed to be order sensitive (https://www.tutorialspoint.com/json/json_data_types.htm). However, according to the source code, when an object in the array is removed, last object in the array is to be used to replace the index it occupies.

This logic could potentially disrupt some functions that take advantage of the ordered nature of array. Do you think this logic should be adjusted to shifting all indices larger than ix left by `1`?

**Comment by kgabis** [comment]
Standard doesn't say anything about removing elements from an array, only that the order of values is significant. But maybe it's a good idea to keep the order since it might be more obvious for users and it's a small change. I'll give it a go.

Also, please use this link when referring to JSON standard: http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf

**Comment by Ron89** [comment]
Since we are on the topic, what do you think of a set of additional API `json_array_insert_x(JSON_Array, size_t idx, value/string/number/boolean/null)` to make it easier to precisely add an entry on a specific index?

**Comment by kgabis** [comment]
```json_array_insert_x``` might be useful, but I'm not planning on growing the json_array api right now.
This issue has been fixed in  https://github.com/kgabis/parson/commit/343fe13f17c36e911b146c1f9f36afad5ee3797f
