### ISSUE TITLE
Make escaping '/' optional

### ISSUE THREAD

**Issue by SanderMertens** [kgabis/parson#90]
If a string is serialized using one of the `json_serialize_to_*` functions, strings that contain the `/` character are automatically escaped. For example, `foo/bar` is serialized as `foo\/bar`. In some situations this looks messy, like when serializing to a human readable/writable JSON configuration file that contains file paths.

I haven't really thought about what a solution should look like. Was more curious to hear what thoughts of other users on this issue are. It's easy enough to monkey patch, but I'd rather not.

SO question where this is discussed (not specific to parson): https://stackoverflow.com/questions/1580647/json-why-are-forward-slashes-escaped

**Comment by kgabis** [comment]
This was already discussed: https://github.com/kgabis/parson/issues/20 https://github.com/kgabis/parson/issues/34
I'm aware this is a bit annoying and at some point I might add a new serialization function that accepts serialization config (or have some global library config, yuck). I'm going to leave this issue open because it's quite likely that someone else will bring it up and I'm curious how many people want this.

**Comment by sharpie7** [comment]
Thanks for leaving this open. I will put my hand up and say that I also am interested in this feature for the same reasons.

**Comment by kgabis** [comment]
I've added a new function to make escaping slashes optional: ```json_set_escape_slashes```.

**Comment by hallard** [comment]
json_set_escape_slashes(0);
Solved my issue, thanks
